common/include/test-array-size.c: Avoid Clang warning
On Clang with warn-error enabled:

test-array-size.c:44:20: error: variable 's0' is not needed and will not be emitted [-Werror,-Wunneeded-internal-declaration]
static const char *s0[] = { };
                   ^
test-array-size.c:45:20: error: variable 's1' is not needed and will not be emitted [-Werror,-Wunneeded-internal-declaration]
static const char *s1[] = { "a" };
                   ^

(etc)

Updates: commit 6e1d0b17842213ef35cb62340db12129d9758527
(cherry picked from nbdkit commit 90f5dbf78bb56cb00d6b3c58fa0a9b390d50e25e)