dump: Fix build on i686
Because we used the wrong printf format, the build would fail on
32 bit architectures but succeed on 64 bit:

dump.c: In function ‘do_dump’:
dump.c:421:21: error: format ‘%zx’ expects argument of type ‘size_t’, but argument 2 has type ‘uint64_t’ {aka ‘long long unsigned int’} [-Werror=format=]
       printf ("%010zx", offset + i);
                ~~~~~^   ~~~~~~~~~~
                %010llx

(cherry picked from commit ce004c329c7fcd6c60d11673b7a5c5ce3414413b)