python: Don't unwrap nbd.Buffer in nbd.py
Prior to this commit, we were unwrapping buf._o in nbd.py, which
causes cryptic errors when the user passes in the wrong type:

$ nbdkit -U - memory 10 --run \
  'nbdsh -u "$uri" -c "h.aio_pread(bytearray(10), 0)"'
Traceback (most recent call last):
...
  File "/usr/lib64/python3.10/site-packages/nbd.py", line 2204, in aio_pread
    return libnbdmod.aio_pread(self._o, buf._o, offset, completion,
AttributeError: 'bytearray' object has no attribute '_o'

or worse, if the user passes in an unrelated type that does have an
attribute "_o" but is not a PyCapsule wrapper:

$ nbdkit -U - memory 10 --run 'nbdsh -u "$uri" -c "
class foo(object):
  def __init__(self):
    self._o = 1
h.aio_pread(foo(), 0)
"'
Traceback (most recent call last):
...
  File "/usr/lib64/python3.10/site-packages/nbd.py", line 2204, in aio_pread
    return libnbdmod.aio_pread(self._o, buf._o, offset, completion,
ValueError: PyCapsule_GetPointer called with invalid PyCapsule object

Change things to instead do the unwrapping in our helper function.
This will also make it easier for an upcoming patch to accept more
types than just nbd.Buffer, with the goal of accepting any python
buffer-like object.  For now, passing in the wrong type still fails,
but with a nicer message:

$ ./run nbdkit -U - memory 10 --run \
  'nbdsh -u "$uri" -c "h.aio_pread(bytearray(10), 0)"'
Traceback (most recent call last):
...
  File "/home/eblake/libnbd/python/nbd.py", line 2204, in aio_pread
    return libnbdmod.aio_pread(self._o, buf, offset, completion, flags)
TypeError: aio_buffer: expecting nbd.Buffer instance

The next patch will clean up the OCaml code, now that none of the
parameter types need alternative text.  The generated code changes as
follows:

| --- python/methods.h.bak	2022-06-07 10:55:47.347442689 -0500
| +++ python/methods.h	2022-06-07 10:55:51.046449200 -0500
| @@ -34,6 +34,7 @@
|      struct sockaddr_storage *, socklen_t *);
|  extern PyObject *nbd_internal_py_get_aio_view (PyObject *, bool);
|  extern int nbd_internal_py_init_aio_buffer (PyObject *);
| +extern PyObject *nbd_internal_py_get_nbd_buffer_type (void);
|
|  static inline struct nbd_handle *
|  get_handle (PyObject *obj)
| --- python/methods.c.bak	2022-06-07 10:55:47.343442682 -0500
| +++ python/methods.c	2022-06-07 10:55:51.062449228 -0500
| @@ -3022,7 +3022,7 @@ nbd_internal_py_aio_pread (PyObject *sel
|    struct nbd_handle *h;
|    int64_t ret;
|    PyObject *py_ret = NULL;
| -  PyObject *buf; /* PyCapsule pointing to struct py_aio_buffer */
| +  PyObject *buf; /* Instance of nbd.Buffer */
|    PyObject *buf_view = NULL; /* PyMemoryView of buf */
|    Py_buffer *py_buf; /* buffer of buf_view */
|    uint64_t offset_u64;
| @@ -3085,7 +3085,7 @@ nbd_internal_py_aio_pread_structured (Py
|    struct nbd_handle *h;
|    int64_t ret;
|    PyObject *py_ret = NULL;
| -  PyObject *buf; /* PyCapsule pointing to struct py_aio_buffer */
| +  PyObject *buf; /* Instance of nbd.Buffer */
|    PyObject *buf_view = NULL; /* PyMemoryView of buf */
|    Py_buffer *py_buf; /* buffer of buf_view */
|    uint64_t offset_u64;
| @@ -3165,7 +3165,7 @@ nbd_internal_py_aio_pwrite (PyObject *se
|    struct nbd_handle *h;
|    int64_t ret;
|    PyObject *py_ret = NULL;
| -  PyObject *buf; /* PyCapsule pointing to struct py_aio_buffer */
| +  PyObject *buf; /* Instance of nbd.Buffer */
|    PyObject *buf_view = NULL; /* PyMemoryView of buf */
|    Py_buffer *py_buf; /* buffer of buf_view */
|    uint64_t offset_u64;
| --- python/nbd.py.bak	2022-06-07 10:55:47.352442698 -0500
| +++ python/nbd.py	2022-06-07 10:55:51.072449246 -0500
| @@ -141,11 +141,11 @@ class Buffer(object):
|
|      def to_bytearray(self):
|          '''Copy an AIO buffer into a bytearray.'''
| -        return libnbdmod.aio_buffer_to_bytearray(self._o)
| +        return libnbdmod.aio_buffer_to_bytearray(self)
|
|      def size(self):
|          '''Return the size of an AIO buffer.'''
| -        return libnbdmod.aio_buffer_size(self._o)
| +        return libnbdmod.aio_buffer_size(self)
|
|      def is_zero(self, offset=0, size=-1):
|          '''Returns true if and only if all bytes in the buffer are zeroes.
| @@ -161,7 +161,7 @@ class Buffer(object):
|          always returns true.  If size > 0, we check the interval
|          [offset..offset+size-1].
|          '''
| -        return libnbdmod.aio_buffer_is_zero(self._o, offset, size)
| +        return libnbdmod.aio_buffer_is_zero(self, offset, size)
|
|
|  class NBD(object):
| @@ -2208,8 +2208,7 @@ class NBD(object):
|      alter which scenarios should await a server reply rather
|      than failing fast.
|  '''
| -        return libnbdmod.aio_pread(self._o, buf._o, offset, completion,
| -                                   flags)
| +        return libnbdmod.aio_pread(self._o, buf, offset, completion, flags)
|
|      def aio_pread_structured(self, buf, offset, chunk, completion=None,
|                               flags=0):
| @@ -2243,8 +2242,8 @@ class NBD(object):
|      alter which scenarios should await a server reply rather
|      than failing fast.
|  '''
| -        return libnbdmod.aio_pread_structured(self._o, buf._o, offset,
| -                                              chunk, completion, flags)
| +        return libnbdmod.aio_pread_structured(self._o, buf, offset, chunk,
| +                                              completion, flags)
|
|      def aio_pwrite(self, buf, offset, completion=None, flags=0):
|          u'''▶ write to the NBD server
| @@ -2267,8 +2266,7 @@ class NBD(object):
|      alter which scenarios should await a server reply rather
|      than failing fast.
|  '''
| -        return libnbdmod.aio_pwrite(self._o, buf._o, offset, completion,
| -                                    flags)
| +        return libnbdmod.aio_pwrite(self._o, buf, offset, completion, flags)
|
|      def aio_disconnect(self, flags=0):
|          u'''▶ disconnect from the NBD server

Reviewed-by: Richard W.M. Jones <rjones@redhat.com>