python: Remove C99-ism which breaks build on RHEL 7
With gcc-4.8.5-44.el7.x86_64:

methods.c: In function 'extent_wrapper':
methods.c:222:3: error: 'for' loop initial declarations are only allowed in C99 mode
   for (size_t i = 0; i < nr_entries; ++i)
   ^
methods.c:222:3: note: use option -std=c99 or -std=gnu99 to compile your code