common/utils/test-vector.c: Remove unused local variable
test-vector.c: In function ‘bench_reserve’:
test-vector.c:125:11: error: unused variable ‘usec’ [-Werror=unused-variable]
  125 |   int64_t usec;
      |           ^~~~
cc1: all warnings being treated as errors

Fixes: commit dc9ae0174ab1384081a57a8d54b10f8147ea6430