build: Silence some cppcheck warnings
I ran:
$ cppcheck --cppcheck-build-dir=cache/cppcheck -q -I . -I common/include/ \
  -I include/ -I lib/ -I common/utils/ -i generator/ .

then inspected the output.  cppcheck correctly flags:

copy/file-ops.c:423:10: portability: 'data' is of type 'void *'. When using void pointers in calculations, the behaviour is undefined. Arithmetic operations on 'void *' is a GNU C extension, which defines the 'sizeof(void)' to be 1. [arithOperationsOnVoidPointer]

examples/copy-libev.c:312:10: style: Local variable 'is_zero' shadows outer function [shadowFunction]

ocaml/nbd-c.c:419:16: portability: Shifting signed 32-bit value by 31 bits is implementation-defined behaviour. See condition at line 416. [shiftTooManyBitsSigned]

It also has several easy-to-fix false positives such as:

lib/opt.c:98:17: error: Uninitialized variable: err [uninitvar]

where the tool failed to see that err was always assigned by the
callback function, or

python/methods.c:357:7: style: Unused variable: ret [unusedVariable]

where the tool prefers redundant ; to delimit use of Python macros
from actual assignments.  I even addressed some of its style
complaints, like:

copy/nbd-ops.c:466:16: style: The scope of the variable 'd' can be reduced...

examples/open-qcow2.c:12:23: style: Parameter 'argv' can be declared with const [constParameter]

common/utils/test-vector.c:53:0: style: The function 'int64_vector_append' is never used. [unusedFunction]

Then there are other false positives that are harder to silence (for
example, it complains about the macros ARRAY_SIZE(), ADD_OVERFLOW(),
MUL_OVERFLOW(); incorrectly suggesting to add const to callback
function signatures; ...)  which I don't try to address here.  So at
this point, it's not yet worth automating a run of cppcheck into our
CI.