api: Silence recent compiler warnings
Looks like I forgot to ./configure --enable-gcc-warnings...

flags.c:36:10: error: unused variable 'i' [-Werror=unused-variable]
generator/states-reply-structured.c:432:24: error: unused variable ‘meta_context’ [-Werror=unused-variable]

Fixes: 55b09667 ("api: Fix nbd_can_meta_context if NBD_OPT_SET_META_CONTEXT fails")
Fixes: 8ece43ea ("interanl: Use vector instead of linked list for meta_contexts")