info/show.c: Don't misuse nbd_get_error or leak nbd_get_export_name
From Coverity:

  Error: RESOURCE_LEAK (CWE-772): [#def42] [important]
  libnbd-1.12.5/info/show.c:69: alloc_fn: Storage is returned from allocation function "nbd_get_export_name".
  libnbd-1.12.5/info/show.c:69: leaked_storage: Failing to save or free storage allocated by "nbd_get_export_name(nbd)" leaks it.
  #   67|         nbd_opt_info (nbd) == -1 &&
  #   68|         nbd_opt_go (nbd) == -1) {
  #   69|->     fprintf (stderr, "%s: %s: %s\n", progname, nbd_get_export_name (nbd),
  #   70|                nbd_get_error ());
  #   71|       return false;

This is quite hard to fix because we were also inadvertantly misusing
nbd_get_error by calling it possibly after calling the
nbd_get_export_name API which might have invalidated the original
error string.  And we weren't checking if nbd_get_export_name was
returning NULL.

Fixes: commit 5473e34fc1fa9ebac288754ea348905be0eac278