RHEL 7: Refuse to compile bindings against Python 2 header files.
On RHEL 7 it is possible to install python3 & python-devel (from
Python 2) together.  If you do this then pkg-config will pick up
Python 2 header files, causing an obscure failure later on.

Instead, force an error which looks like this:

handle.c:29:2: error: #error "These bindings will not work with Python 2.  Recompile using Python 3 or use ./configure --disable-python."

Note on RHEL 7 the way to get around this is to install python36-devel
from EPEL.