common/utils/test-vector.c: Add return to main() function
test-vector.c: In function ‘main’:
test-vector.c:121:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
cc1: all warnings being treated as errors

(cherry picked from nbdkit commit 0a619dd6b0fc74d2e07a27e1c815fcb25dfa6bac)

(cherry picked from commit ea659265972d6dc5534ae4240d498eea1ae6a2f8)