generator: Add abort for unreachable code to avoid GCC warning
With ./configure --enable-gcc-warnings:

  generator/states-reply-structured.c: In function ‘enter_STATE_REPLY_STRUCTURED_REPLY_RESYNC’:
  generator/states-reply-structured.c:511:1: error: control reaches end of non-void function [-Werror=return-type]
  cc1: all warnings being treated as errors

Add a default case that just does abort ().  This should never be
reached.

Fixes: commit 9acf53b109 ("states: Add new RESYNC state ...")