copy: Remove dead store
From Coverity, originally from clang:

  Error: CLANG_WARNING: [#def17]
  libnbd-1.12.5/copy/multi-thread-copying.c:303:7: warning[deadcode.DeadStores]: Value stored to 'is_zeroing' is never read
  #  301|                                   true, w);
  #  302|         fill_dst_range_with_zeroes (command);
  #  303|->       is_zeroing = false;
  #  304|       }
  #  305|     }

I knew this was a dead store when I wrote it, but if clang is going to
produce a warning here we might as well turn it into a comment.

Updates: commit 4058fe1ff03fb41156b67302ba1006b9d06b0218