info: Check return value of asprintf.
nbdinfo.c: In function ‘extent_description’:
nbdinfo.c:793:14: error: ignoring return value of ‘asprintf’ declared with attribute ‘warn_unused_result’ [-Werror=unused-result]
  793 |     default: asprintf (&ret, "backing depth %u", type); return ret;
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Fixes: commit 123a62177b27de40e8b49966cd66a07d18ca0eb0