copy: Fix initialization complaint with ancient GCC on RHEL 7.
RHEL 7 GCC (4.8.5) complains:

multi-thread-copying.c: In function ‘poll_both_ends’:
multi-thread-copying.c:269:10: error: missing braces around initializer [-Werror=missing-braces]
   struct pollfd fds[2] = { 0 };

Replace the initialization with memset which should work for any older
compiler.

(cherry picked from commit a45cea75fc089baa7a1bb9d32145b5e46240c102)