python: Silence nested exception if construction fails
An ignored nested exception is cosmetically undesirable:

$ nbdsh -c 'nbd.NBD(1)'
Exception ignored in: <function NBD.__del__ at 0x7fa726609280>
Traceback (most recent call last):
  File "/usr/lib64/python3.8/site-packages/nbd.py", line 148, in __del__
    libnbdmod.close (self._o)
AttributeError: 'NBD' object has no attribute '_o'
Traceback (most recent call last):
...
  File "<string>", line 1, in <module>
TypeError: __init__() takes 1 positional argument but 2 were given

Fix that, as well as a couple more formatting tweaks noticed in the area.

(cherry picked from commit 2c330575203b06be49d91891598fa72f01bbd415)