fuzzing/libnbd-fuzz-wrapper.c: Fix loop condition
In --write mode we want to continue the loop if _either_ the parent is
alive _or_ the child is feeding data, otherwise we risk creating a
partial test case.

Found by Coverity:

  Error: DEADCODE (CWE-561): [#def41]
  libnbd-1.12.5/fuzzing/libnbd-fuzz-wrapper.c:364: cond_const: Condition "parent_dead", taking false branch. Now the value of "parent_dead" is equal to 0.
  libnbd-1.12.5/fuzzing/libnbd-fuzz-wrapper.c:365: const: At condition "parent_dead", the value of "parent_dead" must be equal to 0.
  libnbd-1.12.5/fuzzing/libnbd-fuzz-wrapper.c:365: dead_error_condition: The condition "parent_dead" cannot be true.
  libnbd-1.12.5/fuzzing/libnbd-fuzz-wrapper.c:365: dead_error_line: Execution cannot reach the expression "-1" inside this statement: "pfds[0].fd = (parent_dead ?...".
  #  363|
  #  364|     while (!parent_dead && rfd[0] >= 0) {
  #  365|->     pfds[0].fd = parent_dead ? -1 : sock;
  #  366|       pfds[0].events = POLLIN;
  #  367|       pfds[0].revents = 0;

Fixes: commit d29c4894a7aca016d0bc391e67d199339341690d