common/utils/test-vector.c: Fix compilation with GCC 4.8 on RHEL 7
test-vector.c: In function ‘bench_reserve’:
test-vector.c:184:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (uint32_t i = 0; i < APPENDS; i++) {
   ^
test-vector.c:184:3: note: use option -std=c99 or -std=gnu99 to compile your code
test-vector.c: In function ‘bench_append’:
test-vector.c:204:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (uint32_t i = 0; i < APPENDS; i++) {
   ^

(cherry picked from nbdkit commit 0c0627edd796d72a2718184856c6c08399b10f62)