examples/batched-read-write.c: Use _exit in signal handler
From Coverity:

  Error: GCC_ANALYZER_WARNING (CWE-479): [#def23]
  libnbd-1.12.5/examples/batched-read-write.c: scope_hint: In function 'alarm_handler'
  libnbd-1.12.5/examples/batched-read-write.c:126:3: warning[-Wanalyzer-unsafe-call-within-signal-handler]: call to 'exit' from within signal handler
  libnbd-1.12.5/examples/batched-read-write.c:126:3: note: '_exit' is a possible signal-safe alternative for 'exit'
  #  124|   {
  #  125|     fprintf (stderr, "alarm fired; deadlock probably occurred\n");
  #  126|->   exit (EXIT_FAILURE);
  #  127|   }
  #  128|

(cherry picked from commit 7de80a96e5a31fa822f78807f871f352f4643476)