Revert "nbdsh: Improve --help and initial banner contents."
  $ nbdsh

  Welcome to nbdsh, the shell for interacting with
  Network Block Device (NBD) servers.

  The ‘nbd’ module has already been imported and there
  is an open NBD handle called ‘h’ in state 'START'.

  h.connect_tcp("remote", "10809")   # Connect to a remote server.
  h.get_size()                       # Get size of the remote disk.
  buf = h.pread(512, 0)              # Read the first sector.
  exit() or Ctrl-D                   # Quit the shell
  help(nbd)                          # Display documentation

  nbd> print(h)
  Traceback (most recent call last):
    File "/usr/lib64/python3.11/code.py", line 90, in runcode
      exec(code, self.locals)
    File "<console>", line 1, in <module>
  NameError: name 'h' is not defined

'h' isn't a global, it's a local variable in the shell() function.

It cannot be used from make_banner().  This is because 'h' is not
created on all paths (eg. if the -n option is used) and you cannot
pass a possibly undefined variable to a function.  I don't think
there's really a way to do this.

This reverts commit 61e88a6515e4af9ece6edc55a22a5966bff94088.