python: Make nbd.Buffer lighter-weight
Instead of storing a PyCapsule in _o and repeatedly doing lookups to
dereference a stored malloc'd pointer, it is easier to just directly
store a Python buffer-like object as _o.  Track initialization via
._init: absent for nbd.Buffer(int), present for
nbd.Buffer.from_bytearray(...) or after we have forced initialization
due to aio_pread or .to_bytearray.  At this point, we are still
copying in and out of .{from,to}_bytearray, but we are getting closer
to reducing the number of copies.  The sheer size in reduced lines of
code is a testament to the ease of doing things closer to Python,
rather than hidden behind unpacking a PyCapsule layer.

Acceptable side effect: nbd.Buffer(-1) changes from:
RuntimeError: length < 0
to
SystemError: Negative size passed to PyByteArray_FromStringAndSize

The generated code changes as follows:

| --- python/methods.h.bak	2022-06-07 11:07:51.330756996 -0500
| +++ python/methods.h	2022-06-07 11:25:06.716653126 -0500
| @@ -62,9 +62,6 @@
|  extern PyObject *nbd_internal_py_close (PyObject *self, PyObject *args);
|  extern PyObject *nbd_internal_py_display_version (PyObject *self, PyObject *args);
|  extern PyObject *nbd_internal_py_alloc_aio_buffer (PyObject *self, PyObject *args);
| -extern PyObject *nbd_internal_py_aio_buffer_from_bytearray (PyObject *self, PyObject *args);
| -extern PyObject *nbd_internal_py_aio_buffer_to_bytearray (PyObject *self, PyObject *args);
| -extern PyObject *nbd_internal_py_aio_buffer_size (PyObject *self, PyObject *args);
|  extern PyObject *nbd_internal_py_aio_buffer_is_zero (PyObject *self, PyObject *args);
|  extern PyObject *nbd_internal_py_set_debug (PyObject *self, PyObject *args);
|  extern PyObject *nbd_internal_py_get_debug (PyObject *self, PyObject *args);
| --- python/nbd.py.bak	2022-06-07 11:07:51.333757002 -0500
| +++ python/nbd.py	2022-06-07 11:25:06.740653165 -0500
| @@ -134,18 +134,21 @@ class Buffer(object):
|          bytearray constructor.  Otherwise, ba is copied.  Either way, the
|          resulting AIO buffer is independent from the original.
|          '''
| -        o = libnbdmod.aio_buffer_from_bytearray(ba)
|          self = cls(0)
| -        self._o = o
| +        self._o = bytearray(ba)
| +        self._init = True
|          return self
|
|      def to_bytearray(self):
|          '''Copy an AIO buffer into a bytearray.'''
| -        return libnbdmod.aio_buffer_to_bytearray(self)
| +        if not hasattr(self, '_init'):
| +            self._o = bytearray(len(self._o))
| +            self._init = True
| +        return bytearray(self._o)
|
|      def size(self):
|          '''Return the size of an AIO buffer.'''
| -        return libnbdmod.aio_buffer_size(self)
| +        return len(self._o)
|
|      def is_zero(self, offset=0, size=-1):
|          '''Returns true if and only if all bytes in the buffer are zeroes.
| @@ -161,7 +164,8 @@ class Buffer(object):
|          always returns true.  If size > 0, we check the interval
|          [offset..offset+size-1].
|          '''
| -        return libnbdmod.aio_buffer_is_zero(self, offset, size)
| +        return libnbdmod.aio_buffer_is_zero(self._o, offset, size,
| +                                            hasattr(self, '_init'))
|
|
|  class NBD(object):

Reviewed-by: Richard W.M. Jones <rjones@redhat.com>