fuse: Check return value from nbd_poll
Before commit 3f257eb606 ("fuse: Issue commands in parallel") nbdfuse
only used synchronous operations, and it checked for errors from each
one.  After this commit we use asynch operations.  We still check the
initial API call (nbd_aio_*), but we no longer checked for errors
happening during the command which would be reported through nbd_poll.

Found by Coverity:

  Error: CHECKED_RETURN (CWE-252): [#def37]
  libnbd-1.12.5/fuse/operations.c:180: check_return: Calling "nbd_poll" without checking return value (as is done elsewhere 5 out of 6 times).
  libnbd-1.12.5/examples/aio-connect-read.c:96: example_checked: Example 1: "nbd_poll(nbd, -1)" has its value checked in "nbd_poll(nbd, -1) == -1".
  libnbd-1.12.5/examples/aio-connect-read.c:128: example_checked: Example 2: "nbd_poll(nbd, -1)" has its value checked in "nbd_poll(nbd, -1) == -1".
  libnbd-1.12.5/examples/strict-structured-reads.c:246: example_checked: Example 3: "nbd_poll(nbd, -1)" has its value checked in "nbd_poll(nbd, -1) == -1".
  libnbd-1.12.5/ocaml/nbd-c.c:2599: example_assign: Example 4: Assigning: "r" = return value from "nbd_poll(h, timeout)".
  libnbd-1.12.5/ocaml/nbd-c.c:2602: example_checked: Example 4 (cont.): "r" has its value checked in "r == -1".
  libnbd-1.12.5/python/methods.c:2806: example_assign: Example 5: Assigning: "ret" = return value from "nbd_poll(h, timeout)".
  libnbd-1.12.5/python/methods.c:2808: example_checked: Example 5 (cont.): "ret" has its value checked in "ret == -1".
  #  178|       /* Dispatch work while there are commands in flight. */
  #  179|       while (thread->in_flight > 0)
  #  180|->       nbd_poll (h, -1);
  #  181|     }
  #  182|

Fixes: commit 3f257eb60636f498649dc41af6a3d6996bd393bd