interop: More test improvements
The x86_64-ubuntu-1804 pipeline still failed, because I used the wrong
python object:
AttributeError: module 'nbd' has no attribute 'shutdown'

And now I have at least one root cause for the
x86_64-opensuse-tumbleweed failure: I captured a log showing that
nbdsh was trying to connect before qemu-nbd had created the socket.
There may still be other things to fix, but such is the joy of
iterative CI debugging...

Fixes: baae33e2