interop: Link TLS tests explicitly with -lgnutls
This fixes the following error which appears on Debian and Ubuntu:

/usr/bin/ld: interop_qemu_nbd_tls_certs-interop.o: undefined reference to symbol 'gnutls_global_set_log_level@@GNUTLS_3_4'
/usr/bin/ld: //usr/lib/x86_64-linux-gnu/libgnutls.so.30: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

Fixes: commit a01f49851969662e2eba84ba583b945adee2d8fe